---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
      dhcp6: false
    enp0s8:
      addresses:
      - 192.168.255.1/30
      routes:
      - to: 192.168.57.0/24
        via: 192.168.255.2
    enp0s19:
      addresses:
      - 192.168.56.10/24
