---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - 192.168.255.2/30
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.1
    enp0s9:
      addresses:
      - 192.168.57.1/28
    enp0s17:
      addresses:
      - 192.168.255.9/30
    enp0s19:
      addresses:
      - 192.168.56.11/24
